/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Compression
 */
export interface Compression {
}

/**
 * Check if a given object implements the Compression interface.
 */
export function instanceOfCompression(value: object): value is Compression {
    return true;
}

export function CompressionFromJSON(json: any): Compression {
    return CompressionFromJSONTyped(json, false);
}

export function CompressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Compression {
    return json;
}

export function CompressionToJSON(json: any): Compression {
    return CompressionToJSONTyped(json, false);
}

export function CompressionToJSONTyped(value?: Compression | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

