/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComparisonStrictParams
 */
export interface ComparisonStrictParams {
    /**
     * 
     * @type {string}
     * @memberof ComparisonStrictParams
     */
    type: ComparisonStrictParamsTypeEnum;
}


/**
 * @export
 */
export const ComparisonStrictParamsTypeEnum = {
    Strict: 'STRICT'
} as const;
export type ComparisonStrictParamsTypeEnum = typeof ComparisonStrictParamsTypeEnum[keyof typeof ComparisonStrictParamsTypeEnum];


/**
 * Check if a given object implements the ComparisonStrictParams interface.
 */
export function instanceOfComparisonStrictParams(value: object): value is ComparisonStrictParams {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ComparisonStrictParamsFromJSON(json: any): ComparisonStrictParams {
    return ComparisonStrictParamsFromJSONTyped(json, false);
}

export function ComparisonStrictParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComparisonStrictParams {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function ComparisonStrictParamsToJSON(json: any): ComparisonStrictParams {
    return ComparisonStrictParamsToJSONTyped(json, false);
}

export function ComparisonStrictParamsToJSONTyped(value?: ComparisonStrictParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

