/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Codes for comparison errors.
 * @export
 */
export const ComparisonErrorCode = {
    ComparisonNotFound: 'COMPARISON_NOT_FOUND',
    SchemaNotFound: 'SCHEMA_NOT_FOUND',
    NotEnoughValues: 'NOT_ENOUGH_VALUES'
} as const;
export type ComparisonErrorCode = typeof ComparisonErrorCode[keyof typeof ComparisonErrorCode];


export function instanceOfComparisonErrorCode(value: any): boolean {
    for (const key in ComparisonErrorCode) {
        if (Object.prototype.hasOwnProperty.call(ComparisonErrorCode, key)) {
            if (ComparisonErrorCode[key as keyof typeof ComparisonErrorCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ComparisonErrorCodeFromJSON(json: any): ComparisonErrorCode {
    return ComparisonErrorCodeFromJSONTyped(json, false);
}

export function ComparisonErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComparisonErrorCode {
    return json as ComparisonErrorCode;
}

export function ComparisonErrorCodeToJSON(value?: ComparisonErrorCode | null): any {
    return value as any;
}

export function ComparisonErrorCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): ComparisonErrorCode {
    return value as ComparisonErrorCode;
}

