/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComparisonValue
 */
export interface ComparisonValue {
    /**
     * 
     * @type {any}
     * @memberof ComparisonValue
     */
    value: any | null;
    /**
     * 
     * @type {string}
     * @memberof ComparisonValue
     */
    filename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ComparisonValue
     */
    path?: string | null;
}

/**
 * Check if a given object implements the ComparisonValue interface.
 */
export function instanceOfComparisonValue(value: object): value is ComparisonValue {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ComparisonValueFromJSON(json: any): ComparisonValue {
    return ComparisonValueFromJSONTyped(json, false);
}

export function ComparisonValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComparisonValue {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function ComparisonValueToJSON(json: any): ComparisonValue {
    return ComparisonValueToJSONTyped(json, false);
}

export function ComparisonValueToJSONTyped(value?: ComparisonValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'filename': value['filename'],
        'path': value['path'],
    };
}

