/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FragmentSizes = {
    Child: 'CHILD',
    Parent: 'PARENT'
} as const;
export type FragmentSizes = typeof FragmentSizes[keyof typeof FragmentSizes];


export function instanceOfFragmentSizes(value: any): boolean {
    for (const key in FragmentSizes) {
        if (Object.prototype.hasOwnProperty.call(FragmentSizes, key)) {
            if (FragmentSizes[key as keyof typeof FragmentSizes] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FragmentSizesFromJSON(json: any): FragmentSizes {
    return FragmentSizesFromJSONTyped(json, false);
}

export function FragmentSizesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FragmentSizes {
    return json as FragmentSizes;
}

export function FragmentSizesToJSON(value?: FragmentSizes | null): any {
    return value as any;
}

export function FragmentSizesToJSONTyped(value: any, ignoreDiscriminator: boolean): FragmentSizes {
    return value as FragmentSizes;
}

