/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Multimodal
 */
export interface Multimodal {
}

/**
 * Check if a given object implements the Multimodal interface.
 */
export function instanceOfMultimodal(value: object): value is Multimodal {
    return true;
}

export function MultimodalFromJSON(json: any): Multimodal {
    return MultimodalFromJSONTyped(json, false);
}

export function MultimodalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Multimodal {
    return json;
}

export function MultimodalToJSON(json: any): Multimodal {
    return MultimodalToJSONTyped(json, false);
}

export function MultimodalToJSONTyped(value?: Multimodal | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

