/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OAuth2GrantType = {
    Password: 'password',
    RefreshToken: 'refresh_token'
} as const;
export type OAuth2GrantType = typeof OAuth2GrantType[keyof typeof OAuth2GrantType];


export function instanceOfOAuth2GrantType(value: any): boolean {
    for (const key in OAuth2GrantType) {
        if (Object.prototype.hasOwnProperty.call(OAuth2GrantType, key)) {
            if (OAuth2GrantType[key as keyof typeof OAuth2GrantType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OAuth2GrantTypeFromJSON(json: any): OAuth2GrantType {
    return OAuth2GrantTypeFromJSONTyped(json, false);
}

export function OAuth2GrantTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2GrantType {
    return json as OAuth2GrantType;
}

export function OAuth2GrantTypeToJSON(value?: OAuth2GrantType | null): any {
    return value as any;
}

export function OAuth2GrantTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OAuth2GrantType {
    return value as OAuth2GrantType;
}

