/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Revision } from './Revision';
import {
    RevisionFromJSON,
    RevisionFromJSONTyped,
    RevisionToJSON,
    RevisionToJSONTyped,
} from './Revision';

/**
 * 
 * @export
 * @interface PaginatedListRevision
 */
export interface PaginatedListRevision {
    /**
     * 
     * @type {number}
     * @memberof PaginatedListRevision
     */
    totalPages: number;
    /**
     * 
     * @type {Array<Revision>}
     * @memberof PaginatedListRevision
     */
    data: Array<Revision>;
}

/**
 * Check if a given object implements the PaginatedListRevision interface.
 */
export function instanceOfPaginatedListRevision(value: object): value is PaginatedListRevision {
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaginatedListRevisionFromJSON(json: any): PaginatedListRevision {
    return PaginatedListRevisionFromJSONTyped(json, false);
}

export function PaginatedListRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'],
        'data': ((json['data'] as Array<any>).map(RevisionFromJSON)),
    };
}

export function PaginatedListRevisionToJSON(json: any): PaginatedListRevision {
    return PaginatedListRevisionToJSONTyped(json, false);
}

export function PaginatedListRevisionToJSONTyped(value?: PaginatedListRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'data': ((value['data'] as Array<any>).map(RevisionToJSON)),
    };
}

