/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequisiteOutput } from './RequisiteOutput';
import {
    RequisiteOutputFromJSON,
    RequisiteOutputFromJSONTyped,
    RequisiteOutputToJSON,
    RequisiteOutputToJSONTyped,
} from './RequisiteOutput';

/**
 * 
 * @export
 * @interface PaginatedListRequisite
 */
export interface PaginatedListRequisite {
    /**
     * 
     * @type {number}
     * @memberof PaginatedListRequisite
     */
    totalPages: number;
    /**
     * 
     * @type {Array<RequisiteOutput>}
     * @memberof PaginatedListRequisite
     */
    data: Array<RequisiteOutput>;
}

/**
 * Check if a given object implements the PaginatedListRequisite interface.
 */
export function instanceOfPaginatedListRequisite(value: object): value is PaginatedListRequisite {
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaginatedListRequisiteFromJSON(json: any): PaginatedListRequisite {
    return PaginatedListRequisiteFromJSONTyped(json, false);
}

export function PaginatedListRequisiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedListRequisite {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'],
        'data': ((json['data'] as Array<any>).map(RequisiteOutputFromJSON)),
    };
}

export function PaginatedListRequisiteToJSON(json: any): PaginatedListRequisite {
    return PaginatedListRequisiteToJSONTyped(json, false);
}

export function PaginatedListRequisiteToJSONTyped(value?: PaginatedListRequisite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'data': ((value['data'] as Array<any>).map(RequisiteOutputToJSON)),
    };
}

