/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Promptroles
 */
export interface Promptroles {
}

/**
 * Check if a given object implements the Promptroles interface.
 */
export function instanceOfPromptroles(value: object): value is Promptroles {
    return true;
}

export function PromptrolesFromJSON(json: any): Promptroles {
    return PromptrolesFromJSONTyped(json, false);
}

export function PromptrolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Promptroles {
    return json;
}

export function PromptrolesToJSON(json: any): Promptroles {
    return PromptrolesToJSONTyped(json, false);
}

export function PromptrolesToJSONTyped(value?: Promptroles | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

