/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadResult
 */
export interface ReadResult {
    /**
     * 
     * @type {Array<string>}
     * @memberof ReadResult
     */
    texts: Array<string>;
}

/**
 * Check if a given object implements the ReadResult interface.
 */
export function instanceOfReadResult(value: object): value is ReadResult {
    if (!('texts' in value) || value['texts'] === undefined) return false;
    return true;
}

export function ReadResultFromJSON(json: any): ReadResult {
    return ReadResultFromJSONTyped(json, false);
}

export function ReadResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadResult {
    if (json == null) {
        return json;
    }
    return {
        
        'texts': json['texts'],
    };
}

export function ReadResultToJSON(json: any): ReadResult {
    return ReadResultToJSONTyped(json, false);
}

export function ReadResultToJSONTyped(value?: ReadResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'texts': value['texts'],
    };
}

