/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequisiteSpecifier } from './RequisiteSpecifier';
import {
    RequisiteSpecifierFromJSON,
    RequisiteSpecifierFromJSONTyped,
    RequisiteSpecifierToJSON,
    RequisiteSpecifierToJSONTyped,
} from './RequisiteSpecifier';

/**
 * 
 * @export
 * @interface Requisites
 */
export interface Requisites {
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Requisites
     */
    byIndex?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Requisites
     */
    byFilename?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Requisites
     */
    byExtension?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Requisites
     */
    byTag?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the Requisites interface.
 */
export function instanceOfRequisites(value: object): value is Requisites {
    return true;
}

export function RequisitesFromJSON(json: any): Requisites {
    return RequisitesFromJSONTyped(json, false);
}

export function RequisitesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Requisites {
    if (json == null) {
        return json;
    }
    return {
        
        'byIndex': json['by_index'] == null ? undefined : json['by_index'],
        'byFilename': json['by_filename'] == null ? undefined : json['by_filename'],
        'byExtension': json['by_extension'] == null ? undefined : json['by_extension'],
        'byTag': json['by_tag'] == null ? undefined : json['by_tag'],
    };
}

export function RequisitesToJSON(json: any): Requisites {
    return RequisitesToJSONTyped(json, false);
}

export function RequisitesToJSONTyped(value?: Requisites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by_index': value['byIndex'],
        'by_filename': value['byFilename'],
        'by_extension': value['byExtension'],
        'by_tag': value['byTag'],
    };
}

