/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseSchemaOutput } from './ResponseSchemaOutput';
import {
    ResponseSchemaOutputFromJSON,
    ResponseSchemaOutputFromJSONTyped,
    ResponseSchemaOutputToJSON,
    ResponseSchemaOutputToJSONTyped,
} from './ResponseSchemaOutput';
import type { Strategy } from './Strategy';
import {
    StrategyFromJSON,
    StrategyFromJSONTyped,
    StrategyToJSON,
    StrategyToJSONTyped,
} from './Strategy';

/**
 * 
 * @export
 * @interface RequisiteOutput
 */
export interface RequisiteOutput {
    /**
     * 
     * @type {string}
     * @memberof RequisiteOutput
     */
    id?: string;
    /**
     * 
     * @type {Strategy}
     * @memberof RequisiteOutput
     */
    strategy: Strategy;
    /**
     * 
     * @type {string}
     * @memberof RequisiteOutput
     */
    user?: string | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof RequisiteOutput
     */
    embeddings?: Array<any> | null;
    /**
     * 
     * @type {ResponseSchemaOutput}
     * @memberof RequisiteOutput
     */
    schema: ResponseSchemaOutput;
}

/**
 * Check if a given object implements the RequisiteOutput interface.
 */
export function instanceOfRequisiteOutput(value: object): value is RequisiteOutput {
    if (!('strategy' in value) || value['strategy'] === undefined) return false;
    if (!('schema' in value) || value['schema'] === undefined) return false;
    return true;
}

export function RequisiteOutputFromJSON(json: any): RequisiteOutput {
    return RequisiteOutputFromJSONTyped(json, false);
}

export function RequisiteOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequisiteOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'] == null ? undefined : json['_id'],
        'strategy': StrategyFromJSON(json['strategy']),
        'user': json['user'] == null ? undefined : json['user'],
        'embeddings': json['embeddings'] == null ? undefined : json['embeddings'],
        'schema': ResponseSchemaOutputFromJSON(json['schema']),
    };
}

export function RequisiteOutputToJSON(json: any): RequisiteOutput {
    return RequisiteOutputToJSONTyped(json, false);
}

export function RequisiteOutputToJSONTyped(value?: RequisiteOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'strategy': StrategyToJSON(value['strategy']),
        'user': value['user'],
        'embeddings': value['embeddings'],
        'schema': ResponseSchemaOutputToJSON(value['schema']),
    };
}

