/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequisitePropertyInputEnumInner } from './RequisitePropertyInputEnumInner';
import {
    RequisitePropertyInputEnumInnerFromJSON,
    RequisitePropertyInputEnumInnerFromJSONTyped,
    RequisitePropertyInputEnumInnerToJSON,
    RequisitePropertyInputEnumInnerToJSONTyped,
} from './RequisitePropertyInputEnumInner';

/**
 * 
 * @export
 * @interface RequisitePropertyInput
 */
export interface RequisitePropertyInput {
    /**
     * 
     * @type {string}
     * @memberof RequisitePropertyInput
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof RequisitePropertyInput
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: RequisitePropertyInput; }}
     * @memberof RequisitePropertyInput
     */
    properties?: { [key: string]: RequisitePropertyInput; };
    /**
     * 
     * @type {Array<RequisitePropertyInputEnumInner>}
     * @memberof RequisitePropertyInput
     */
    _enum?: Array<RequisitePropertyInputEnumInner>;
}

/**
 * Check if a given object implements the RequisitePropertyInput interface.
 */
export function instanceOfRequisitePropertyInput(value: object): value is RequisitePropertyInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RequisitePropertyInputFromJSON(json: any): RequisitePropertyInput {
    return RequisitePropertyInputFromJSONTyped(json, false);
}

export function RequisitePropertyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequisitePropertyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'properties': json['properties'] == null ? undefined : (mapValues(json['properties'], RequisitePropertyInputFromJSON)),
        '_enum': json['enum'] == null ? undefined : ((json['enum'] as Array<any>).map(RequisitePropertyInputEnumInnerFromJSON)),
    };
}

export function RequisitePropertyInputToJSON(json: any): RequisitePropertyInput {
    return RequisitePropertyInputToJSONTyped(json, false);
}

export function RequisitePropertyInputToJSONTyped(value?: RequisitePropertyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'description': value['description'],
        'properties': value['properties'] == null ? undefined : (mapValues(value['properties'], RequisitePropertyInputToJSON)),
        'enum': value['_enum'] == null ? undefined : ((value['_enum'] as Array<any>).map(RequisitePropertyInputEnumInnerToJSON)),
    };
}

