/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequisitePropertyInputEnumInner
 */
export interface RequisitePropertyInputEnumInner {
}

/**
 * Check if a given object implements the RequisitePropertyInputEnumInner interface.
 */
export function instanceOfRequisitePropertyInputEnumInner(value: object): value is RequisitePropertyInputEnumInner {
    return true;
}

export function RequisitePropertyInputEnumInnerFromJSON(json: any): RequisitePropertyInputEnumInner {
    return RequisitePropertyInputEnumInnerFromJSONTyped(json, false);
}

export function RequisitePropertyInputEnumInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequisitePropertyInputEnumInner {
    return json;
}

export function RequisitePropertyInputEnumInnerToJSON(json: any): RequisitePropertyInputEnumInner {
    return RequisitePropertyInputEnumInnerToJSONTyped(json, false);
}

export function RequisitePropertyInputEnumInnerToJSONTyped(value?: RequisitePropertyInputEnumInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

