/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Requisites
 */
export interface Requisites {
}

/**
 * Check if a given object implements the Requisites interface.
 */
export function instanceOfRequisites(value: object): value is Requisites {
    return true;
}

export function RequisitesFromJSON(json: any): Requisites {
    return RequisitesFromJSONTyped(json, false);
}

export function RequisitesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Requisites {
    return json;
}

export function RequisitesToJSON(json: any): Requisites {
    return RequisitesToJSONTyped(json, false);
}

export function RequisitesToJSONTyped(value?: Requisites | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

