/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequisiteSpecifier
 */
export interface RequisiteSpecifier {
    [key: string]: any | any;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RequisiteSpecifier
     */
    byIndex?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RequisiteSpecifier
     */
    byFilename?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RequisiteSpecifier
     */
    byExtension?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RequisiteSpecifier
     */
    byTag?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the RequisiteSpecifier interface.
 */
export function instanceOfRequisiteSpecifier(value: object): value is RequisiteSpecifier {
    return true;
}

export function RequisiteSpecifierFromJSON(json: any): RequisiteSpecifier {
    return RequisiteSpecifierFromJSONTyped(json, false);
}

export function RequisiteSpecifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequisiteSpecifier {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'byIndex': json['by_index'] == null ? undefined : json['by_index'],
        'byFilename': json['by_filename'] == null ? undefined : json['by_filename'],
        'byExtension': json['by_extension'] == null ? undefined : json['by_extension'],
        'byTag': json['by_tag'] == null ? undefined : json['by_tag'],
    };
}

export function RequisiteSpecifierToJSON(json: any): RequisiteSpecifier {
    return RequisiteSpecifierToJSONTyped(json, false);
}

export function RequisiteSpecifierToJSONTyped(value?: RequisiteSpecifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'by_index': value['byIndex'],
        'by_filename': value['byFilename'],
        'by_extension': value['byExtension'],
        'by_tag': value['byTag'],
    };
}

