/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserType } from './UserType';
import {
    UserTypeFromJSON,
    UserTypeFromJSONTyped,
    UserTypeToJSON,
    UserTypeToJSONTyped,
} from './UserType';

/**
 * 
 * @export
 * @interface RequestUserPartial
 */
export interface RequestUserPartial {
    /**
     * 
     * @type {string}
     * @memberof RequestUserPartial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestUserPartial
     */
    name: string;
    /**
     * 
     * @type {UserType}
     * @memberof RequestUserPartial
     */
    type?: UserType | null;
    /**
     * 
     * @type {string}
     * @memberof RequestUserPartial
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestUserPartial
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof RequestUserPartial
     */
    embeddingModel?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RequestUserPartial
     */
    disabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RequestUserPartial
     */
    maxFiles?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUserPartial
     */
    expireRevisionSeconds?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RequestUserPartial
     */
    ownerEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestUserPartial
     */
    role?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RequestUserPartial
     */
    includeReadResult?: boolean;
}



/**
 * Check if a given object implements the RequestUserPartial interface.
 */
export function instanceOfRequestUserPartial(value: object): value is RequestUserPartial {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function RequestUserPartialFromJSON(json: any): RequestUserPartial {
    return RequestUserPartialFromJSONTyped(json, false);
}

export function RequestUserPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestUserPartial {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'] == null ? undefined : json['_id'],
        'name': json['name'],
        'type': json['type'] == null ? undefined : UserTypeFromJSON(json['type']),
        'description': json['description'] == null ? undefined : json['description'],
        'model': json['model'],
        'embeddingModel': json['embedding_model'] == null ? undefined : json['embedding_model'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'maxFiles': json['max_files'] == null ? undefined : json['max_files'],
        'expireRevisionSeconds': json['expire_revision_seconds'] == null ? undefined : json['expire_revision_seconds'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'role': json['role'] == null ? undefined : json['role'],
        'includeReadResult': json['include_read_result'] == null ? undefined : json['include_read_result'],
    };
}

export function RequestUserPartialToJSON(json: any): RequestUserPartial {
    return RequestUserPartialToJSONTyped(json, false);
}

export function RequestUserPartialToJSONTyped(value?: RequestUserPartial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'name': value['name'],
        'type': UserTypeToJSON(value['type']),
        'description': value['description'],
        'model': value['model'],
        'embedding_model': value['embeddingModel'],
        'disabled': value['disabled'],
        'max_files': value['maxFiles'],
        'expire_revision_seconds': value['expireRevisionSeconds'],
        'owner_email': value['ownerEmail'],
        'role': value['role'],
        'include_read_result': value['includeReadResult'],
    };
}

