/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequisiteCompleteParams
 */
export interface RequisiteCompleteParams {
    /**
     * 
     * @type {string}
     * @memberof RequisiteCompleteParams
     */
    type?: RequisiteCompleteParamsTypeEnum;
}


/**
 * @export
 */
export const RequisiteCompleteParamsTypeEnum = {
    Complete: 'complete'
} as const;
export type RequisiteCompleteParamsTypeEnum = typeof RequisiteCompleteParamsTypeEnum[keyof typeof RequisiteCompleteParamsTypeEnum];


/**
 * Check if a given object implements the RequisiteCompleteParams interface.
 */
export function instanceOfRequisiteCompleteParams(value: object): value is RequisiteCompleteParams {
    return true;
}

export function RequisiteCompleteParamsFromJSON(json: any): RequisiteCompleteParams {
    return RequisiteCompleteParamsFromJSONTyped(json, false);
}

export function RequisiteCompleteParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequisiteCompleteParams {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function RequisiteCompleteParamsToJSON(json: any): RequisiteCompleteParams {
    return RequisiteCompleteParamsToJSONTyped(json, false);
}

export function RequisiteCompleteParamsToJSONTyped(value?: RequisiteCompleteParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

