/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequisitePropertyOutput } from './RequisitePropertyOutput';
import {
    RequisitePropertyOutputFromJSON,
    RequisitePropertyOutputFromJSONTyped,
    RequisitePropertyOutputToJSON,
    RequisitePropertyOutputToJSONTyped,
} from './RequisitePropertyOutput';

/**
 * 
 * @export
 * @interface ResponseSchemaOutput
 */
export interface ResponseSchemaOutput {
    /**
     * 
     * @type {string}
     * @memberof ResponseSchemaOutput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSchemaOutput
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSchemaOutput
     */
    type: string;
    /**
     * 
     * @type {{ [key: string]: RequisitePropertyOutput; }}
     * @memberof ResponseSchemaOutput
     */
    properties: { [key: string]: RequisitePropertyOutput; };
    /**
     * 
     * @type {Array<string>}
     * @memberof ResponseSchemaOutput
     */
    required?: Array<string>;
}

/**
 * Check if a given object implements the ResponseSchemaOutput interface.
 */
export function instanceOfResponseSchemaOutput(value: object): value is ResponseSchemaOutput {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function ResponseSchemaOutputFromJSON(json: any): ResponseSchemaOutput {
    return ResponseSchemaOutputFromJSONTyped(json, false);
}

export function ResponseSchemaOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseSchemaOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'],
        'properties': (mapValues(json['properties'], RequisitePropertyOutputFromJSON)),
        'required': json['required'] == null ? undefined : json['required'],
    };
}

export function ResponseSchemaOutputToJSON(json: any): ResponseSchemaOutput {
    return ResponseSchemaOutputToJSONTyped(json, false);
}

export function ResponseSchemaOutputToJSONTyped(value?: ResponseSchemaOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'type': value['type'],
        'properties': (mapValues(value['properties'], RequisitePropertyOutputToJSON)),
        'required': value['required'],
    };
}

