/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of document revision.
 * @export
 */
export const RevisionStatus = {
    Pending: 'PENDING',
    Complete: 'COMPLETE',
    Failed: 'FAILED'
} as const;
export type RevisionStatus = typeof RevisionStatus[keyof typeof RevisionStatus];


export function instanceOfRevisionStatus(value: any): boolean {
    for (const key in RevisionStatus) {
        if (Object.prototype.hasOwnProperty.call(RevisionStatus, key)) {
            if (RevisionStatus[key as keyof typeof RevisionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RevisionStatusFromJSON(json: any): RevisionStatus {
    return RevisionStatusFromJSONTyped(json, false);
}

export function RevisionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevisionStatus {
    return json as RevisionStatus;
}

export function RevisionStatusToJSON(value?: RevisionStatus | null): any {
    return value as any;
}

export function RevisionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RevisionStatus {
    return value as RevisionStatus;
}

