/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevisionTagSpecifier
 */
export interface RevisionTagSpecifier {
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RevisionTagSpecifier
     */
    byIndex?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RevisionTagSpecifier
     */
    byFilename?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the RevisionTagSpecifier interface.
 */
export function instanceOfRevisionTagSpecifier(value: object): value is RevisionTagSpecifier {
    return true;
}

export function RevisionTagSpecifierFromJSON(json: any): RevisionTagSpecifier {
    return RevisionTagSpecifierFromJSONTyped(json, false);
}

export function RevisionTagSpecifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevisionTagSpecifier {
    if (json == null) {
        return json;
    }
    return {
        
        'byIndex': json['by_index'] == null ? undefined : json['by_index'],
        'byFilename': json['by_filename'] == null ? undefined : json['by_filename'],
    };
}

export function RevisionTagSpecifierToJSON(json: any): RevisionTagSpecifier {
    return RevisionTagSpecifierToJSONTyped(json, false);
}

export function RevisionTagSpecifierToJSONTyped(value?: RevisionTagSpecifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by_index': value['byIndex'],
        'by_filename': value['byFilename'],
    };
}

