/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Specifies one attribute to project in a revision.
 * @export
 * @interface RevisionProjection
 */
export interface RevisionProjection {
    /**
     * 
     * @type {string}
     * @memberof RevisionProjection
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RevisionProjection
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof RevisionProjection
     */
    attribute: string;
}

/**
 * Check if a given object implements the RevisionProjection interface.
 */
export function instanceOfRevisionProjection(value: object): value is RevisionProjection {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('attribute' in value) || value['attribute'] === undefined) return false;
    return true;
}

export function RevisionProjectionFromJSON(json: any): RevisionProjection {
    return RevisionProjectionFromJSONTyped(json, false);
}

export function RevisionProjectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevisionProjection {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'filename': json['filename'],
        'attribute': json['attribute'],
    };
}

export function RevisionProjectionToJSON(json: any): RevisionProjection {
    return RevisionProjectionToJSONTyped(json, false);
}

export function RevisionProjectionToJSONTyped(value?: RevisionProjection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'filename': value['filename'],
        'attribute': value['attribute'],
    };
}

