/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Codes for common document revision errors.
 * @export
 */
export const RevisionErrorCode = {
    UnsupportedFiletype: 'UNSUPPORTED_FILETYPE',
    NoFilenameProvided: 'NO_FILENAME_PROVIDED'
} as const;
export type RevisionErrorCode = typeof RevisionErrorCode[keyof typeof RevisionErrorCode];


export function instanceOfRevisionErrorCode(value: any): boolean {
    for (const key in RevisionErrorCode) {
        if (Object.prototype.hasOwnProperty.call(RevisionErrorCode, key)) {
            if (RevisionErrorCode[key as keyof typeof RevisionErrorCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RevisionErrorCodeFromJSON(json: any): RevisionErrorCode {
    return RevisionErrorCodeFromJSONTyped(json, false);
}

export function RevisionErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevisionErrorCode {
    return json as RevisionErrorCode;
}

export function RevisionErrorCodeToJSON(value?: RevisionErrorCode | null): any {
    return value as any;
}

export function RevisionErrorCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): RevisionErrorCode {
    return value as RevisionErrorCode;
}

